### Циклы while и for

<div style="border:solid green 2px; padding: 20px">
 Для различных операций, связанных с перебором индексируемых элементов структур данных, традиционно используются циклы while и for.
</div>

In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
    n += 1
    print(n, " ")
end

1 2 3 4 5 6 7 8 9 10 

In [3]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [5]:
# рассмотрим те же самые примеры с циклом for
for n in 1:2:10
    println(n)
end

1
3
5
7
9


In [7]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


<div style="border:solid green 2px; padding: 20px">
    Пример использования цикла for для создания двумерного массива, в котором значение каждой записи является суммой индексов строки и столбца:
</div>

In [9]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))

# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [11]:
# Другая реализация этого же примера:
# инициализация массива m x n из нулей:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [ ]:
# Ещё одна реализация этого же примера:
C = [i + j for i in 1:m, j in 1:n]
C

### Условные выражения

- Довольно часто при решении задач требуется проверить выполнение тех или иных условий. Для этого используют условные выражения

<div style="border:solid green 2px; padding: 20px">
    пусть для заданного числа 𝑁 требуется вывести слово «Fizz», если 𝑁 делится
на 3, «Buzz», если 𝑁 делится на 5, и «FizzBuzz», если 𝑁 делится на 3 и 5.
</div>

In [13]:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
# допустм N равно 5
N = 5

if (N % 3 == 0) && (N % 5 == 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

Buzz


In [15]:
# пример использования тернарного оператора
x = 5
y = 10
(x > y) ? x : y

10

### Функции

- Julia дает нам несколько разных способов написать функцию. Первый требует ключевых слов function и end.

In [17]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end
sayhi("Nastya")

Hi Nastya, it's great to see you!


In [19]:
# функция возведения в квадрат:
function f(x)
    x^2
end
f(4)

16

In [21]:
# в качестве альтернативы 
sayhi2(name) = println("Hi $name, it's great to see you!")
sayhi2("Sasha")

Hi Sasha, it's great to see you!


In [23]:
f2(x) = x^2
f2(42)

1764

### Также можно объявить вышеперечисленные функции как анонимные

In [25]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
sayhi3("Bernard")

Hi Bernard, it's great to see you!


In [27]:
f3 = x -> x^2
f3(34)

1156

<div style="border:solid green 2px; padding: 20px">
По соглашению в Julia функции, сопровождаемые восклицательным знаком, изменяют
свое содержимое, а функции без восклицательного знака не делают этого.
</div>

In [29]:
# задаём массив v:
v = [3, 5, 2]
sort(v)
v

3-element Vector{Int64}:
 3
 5
 2

In [31]:
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

<div style="border:solid green 2px; padding: 20px">
В Julia функция map является функцией высшего порядка, которая принимает функцию в качестве одного из своих входных аргументов и применяет эту функцию к каждому элементу структуры данных, которая ей передаётся также в качестве аргумента.
</div>

In [33]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [35]:
# работа map с анонимной функцией
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

<div style="border:solid green 2px; padding: 20px">
Функция broadcast() будет пытаться привести все объекты к общему измерению, map() будет напрямую применять данную функцию поэлементно.
</div>

In [37]:
f(x) = x^2
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [39]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [41]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [43]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [45]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [47]:
# аналогичная запись
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

### Сторонние библиотеки в Julia

In [49]:
import Pkg
Pkg.add("Example")

    Updating registry at `C:\Users\GanZL\.julia\registries\General.toml`
   Resolving package versions...
   Installed Example ─ v0.5.5
    Updating `C:\Users\GanZL\.julia\environments\v1.11\Project.toml`
  [7876af07] + Example v0.5.5
    Updating `C:\Users\GanZL\.julia\environments\v1.11\Manifest.toml`
  [7876af07] + Example v0.5.5
Precompiling project...
   1600.0 ms  ✓ Example
  1 dependency successfully precompiled in 3 seconds. 45 already precompiled.


In [51]:
Pkg.add("Colors")
using Colors

   Resolving package versions...
   Installed FixedPointNumbers ─ v0.8.5
   Installed Reexport ────────── v1.2.2
   Installed ColorTypes ──────── v0.12.0
   Installed Colors ──────────── v0.13.0
   Installed Statistics ──────── v1.11.1
    Updating `C:\Users\GanZL\.julia\environments\v1.11\Project.toml`
  [5ae59095] + Colors v0.13.0
    Updating `C:\Users\GanZL\.julia\environments\v1.11\Manifest.toml`
  [3da002f7] + ColorTypes v0.12.0
  [5ae59095] + Colors v0.13.0
  [53c48c17] + FixedPointNumbers v0.8.5
  [189a3867] + Reexport v1.2.2
  [10745b16] + Statistics v1.11.1
  [37e2e46d] + LinearAlgebra v1.11.0
  [e66e0078] + CompilerSupportLibraries_jll v1.1.1+0
  [4536629a] + OpenBLAS_jll v0.3.27+1
  [8e850b90] + libblastrampoline_jll v5.11.0+0
Precompiling project...
    386.8 ms  ✓ Reexport
    499.1 ms  ✓ Statistics
   1443.3 ms  ✓ FixedPointNumbers
   1060.9 ms  ✓ ColorTypes
    494.8 ms  ✓ ColorTypes → StyledStringsExt
   2448.9 ms  ✓ Colors
  6 dependencies successfully precompiled in 

In [53]:
palette = distinguishable_colors(100)

In [55]:
rand(palette, 3, 3)

### Задания для самостоятельного выполнения

<div style="border:solid green 2px; padding: 20px">
    
1. Используя циклы while и for:
    - выведите на экран целые числа от 1 до 100 и напечатайте их квадраты;
    - создайте словарь squares, который будет содержать целые числа в качестве ключей и квадраты в качестве их пар-значений;
    - создайте массив squares_arr, содержащий квадраты всех чисел от 1 до 100.
    
</div>

In [57]:
for i in 1:1:100
    println(i)
end

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [59]:
i = 1
while i <= 100
    println(i^2)
    i += 1
end

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576
625
676
729
784
841
900
961
1024
1089
1156
1225
1296
1369
1444
1521
1600
1681
1764
1849
1936
2025
2116
2209
2304
2401
2500
2601
2704
2809
2916
3025
3136
3249
3364
3481
3600
3721
3844
3969
4096
4225
4356
4489
4624
4761
4900
5041
5184
5329
5476
5625
5776
5929
6084
6241
6400
6561
6724
6889
7056
7225
7396
7569
7744
7921
8100
8281
8464
8649
8836
9025
9216
9409
9604
9801
10000


In [61]:
# инициализируем словарь
squares = Dict{Int64, Int64}()
# занесем значения в словарь
for i in 1:1:100
    push!(squares, i => i^2)
end
pairs(squares)

Dict{Int64, Int64} with 100 entries:
  5  => 25
  56 => 3136
  35 => 1225
  55 => 3025
  60 => 3600
  30 => 900
  32 => 1024
  6  => 36
  67 => 4489
  45 => 2025
  73 => 5329
  64 => 4096
  90 => 8100
  4  => 16
  13 => 169
  54 => 2916
  63 => 3969
  86 => 7396
  91 => 8281
  62 => 3844
  58 => 3364
  52 => 2704
  12 => 144
  28 => 784
  75 => 5625
  ⋮  => ⋮

In [143]:
# создадим массив из целых чисел от 1 до 100
numbers = []
for i in 1:1:100
    append!(numbers, i)
end

# возведем в квадрат кажое число из массива numbers
squares_arr = []
i = 1
while i <= length(numbers)
    append!(squares_arr, numbers[i]^2)
    i += 1
end
squares_arr

100-element Vector{Any}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

<div style="border:solid green 2px; padding: 20px">
2. Напишите условный оператор, который печатает число, если число чётное, и строку «нечётное», если число нечётное. Перепишите код, используя тернарный оператор.
</div>

In [63]:
N = 5
if N % 2 == 0
    println("Четное число")
else
    println("Нечетное число")
end

Нечетное число


In [65]:
N = 4
(N % 2 == 0) ? println("Четное число") : println("Нечетное число")

Четное число


<div style="border:solid green 2px; padding: 20px">
3. Напишите функцию add_one, которая добавляет 1 к своему входу.
</div>

In [67]:
function add_one(X)
    X + 1
end
add_one(5)

6

<div style="border:solid green 2px; padding: 20px">
4. Используйте map() или broadcast() для задания матрицы 𝐴, каждый элемент которой увеличивается на единицу по сравнению с предыдущим.
</div>

In [69]:
X = fill(1, 4 * 4)
Y = collect(0:(length(X) - 1))
X = reshape(map(+, X, Y), (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

<div style="border:solid green 2px; padding: 20px">
5. Задайте матрицу 𝐴 
</div>

In [71]:
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [73]:
# возведение в степень 3
A^3

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [75]:
# заменим 3 столбец матрицы A на сумму второго и третьего столбца
for i in 7:1:9
    A[i] += A[i-3]
end
A

3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

<div style="border:solid green 2px; padding: 20px">
6. Создайте матрицу 𝐵 с элементами 𝐵𝑖1 = 10, 𝐵𝑖2 = −10, 𝐵𝑖3 = 10, 𝑖 = 1, 2, … , 15.
Вычислите матрицу 𝐶 = (𝐵^𝑇)𝐵.
</div>

In [77]:
# объявим матрицу B
B = Array{Int32, 2}(undef, 15, 3)

# заполним матрицу в соответствии с заданием
for i in 1:1:15
    B[i, 1] = 10
    B[i, 2] = -10
    B[i, 3] = 10
end
B

15×3 Matrix{Int32}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [79]:
# вычислим матрицу 
C = (B')*B
C

3×3 Matrix{Int32}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

<div style="border:solid green 2px; padding: 20px">
7. Создайте матрицу 𝑍 размерности 6 × 6, все элементы которой равны нулю, и матрицу 𝐸, все элементы которой равны 1. Используя цикл while или for и закономерности расположения элементов, создайте следующие матрицы размерности 6 × 6.
</div>

In [81]:
z = zeros(Int64, 6, 6)

6×6 Matrix{Int64}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [83]:
E = ones(Int64, 6, 6)

6×6 Matrix{Int64}:
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1
 1  1  1  1  1  1

In [85]:
z1 = zeros(Int64, 6, 6)
for i in 1:1:6
    if i != 1 
        z1[i, i - 1] = E[i, i - 1]
    end
    if i != 6
        z1[i, i + 1] = E[i, i + 1]
    end
end
z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [87]:
z2 = zeros(Int64, 6, 6)
for i in 1:1:6
    z2[i,i] = 1
    if(i+2 <= 6) z2[i,i + 2] = E[i, i + 2] end
    if(i-2 >= 1) z2[i, i - 2] = E[i, i - 2] end
end
z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 1  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [89]:
z3 = zeros(Int64, 6, 6)
for i in 1:1:6
    z3[i,7-i] = 1
    if((7-i+2) <= 6) z3[i,9 - i] = E[i,9 - i] end
    if((7-i-2) >= 1) z3[i, 5 - i] = E[i, 5 - i] end
end
z3

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  0
 1  0  1  0  0  0

In [91]:
z4 = zeros(Int64, 6, 6)
for i in 1:1:6
    z4[i,i] = 1
    if(i+2 <= 6) z4[i, i + 2] = E[i, i + 2] end
    if(i-2 >= 1) z4[i, i - 2] = E[i, i - 2] end
    if(i+4 <= 6) z4[i, i + 4] = E[i, i + 4] end
    if(i-4 >= 1) z4[i, i - 4] = E[i, i - 4] end
end
z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

<div style="border:solid green 2px; padding: 20px">
8. Напишите свою функцию, аналогичную функции outer() языка R. Функция должна иметь следующий интерфейс: outer(x,y,operation).
</div>

In [93]:
function outer(x, y, operation)
    if (ndims(x) == 1) x = reshape(x, (size(x, 1), size(x, 2))) end
    if (ndims(y) == 1) y = reshape(y, (size(y, 1), size(y, 2))) end
    c = zeros(size(x)[1], size(y)[2])
    for i in 1:size(x)[1], j in 1:size(y)[2], k in 1:size(x)[2]
        c[i, j] += operation(x[i, k], y[k, j])
    end
    return c
end

outer (generic function with 1 method)

In [95]:
# проверим на данной матрице работу функции
X = [[1 1 3]; [5 2 6]; [-2 -1 -3]]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [97]:
X * X

3×3 Matrix{Int64}:
  0   0   0
  3   3   9
 -1  -1  -3

In [99]:
outer(X, X, *)

3×3 Matrix{Float64}:
  0.0   0.0   0.0
  3.0   3.0   9.0
 -1.0  -1.0  -3.0

In [101]:
# Построим первую матрицу
A1 = outer(collect(0:4), collect(0:4)', +)

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  5.0
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0

In [103]:
# построим вторую матрицу
A2 = outer(collect(0:4), collect(1:5)', ^)

5×5 Matrix{Float64}:
 0.0   0.0   0.0    0.0     0.0
 1.0   1.0   1.0    1.0     1.0
 2.0   4.0   8.0   16.0    32.0
 3.0   9.0  27.0   81.0   243.0
 4.0  16.0  64.0  256.0  1024.0

In [105]:
# построим третью матрицу
# возьмем остаток от деления на 5
A3 = outer(collect(0:4), collect(0:4)', +).%5

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  0.0
 2.0  3.0  4.0  0.0  1.0
 3.0  4.0  0.0  1.0  2.0
 4.0  0.0  1.0  2.0  3.0

In [107]:
# построим четвертую матрицу
# возьмем остаток от деления на 10
A4 = outer(collect(0:9), collect(0: 9)', +).%10

10×10 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0
 2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0
 3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0
 4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0
 5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0
 6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0
 7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0
 8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0
 9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [109]:
# построим пятую матрицу
# возьмем остаток от деления на 9
A5 = outer(collect(0:8), collect(-9:-1)', -).%9

9×9 Matrix{Float64}:
 0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0
 1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0
 2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0
 3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0
 4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0
 5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0
 6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0
 7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0
 8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0

<div style="border:solid green 2px; padding: 20px">
9. Решите следующую систему линейных уравнений с 5 неизвестными.
</div>

In [111]:
# зададим коэффициенты из системы уравнений
array_system = Array{Int64, 2}(undef, 5, 5)
m = 5
n = 5

for i in 1:1:m
    for j in 1:1:n
        array_system[i, j] = 1 + abs(i - j)
    end
end
println(round.(Int32, array_system))


# обозначим ответы
answers = [7; -1; -3; 5; 17]

Int32[1 2 3 4 5; 2 1 2 3 4; 3 2 1 2 3; 4 3 2 1 2; 5 4 3 2 1]


5-element Vector{Int64}:
  7
 -1
 -3
  5
 17

In [113]:
# с помощью обратной матрицы получим решение данной матрицы
array_system_inv = inv(array_system)
round.(Int, array_system_inv)
x_n = round.(Int, array_system_inv * answers)

5-element Vector{Int64}:
 -2
  3
  5
  2
 -4

<div style="border:solid green 2px; padding: 20px">
    
10. Создайте матрицу 𝑀 размерности 6 × 10, элементами которой являются целые числа, выбранные случайным образом с повторениями из совокупности 1, 2, … , 10.
    
</div>

In [115]:
M = rand(1:10, 6, 10)

6×10 Matrix{Int64}:
 4   1  10  7  4   7  2  3  3  8
 2  10   3  3  3   8  3  3  3  6
 4   3   4  4  7   2  6  2  1  7
 6   6   3  2  9   5  1  3  7  2
 3   2   3  7  6   8  4  8  1  5
 5   7   5  5  9  10  9  4  7  4

- Найдите число элементов в каждой строке матрицы 𝑀, которые больше числа 𝑁 (например, 𝑁 = 4). 

In [125]:
N = 6
for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] > N
            count += 1
        end
    end
    println("Количество элементов больше ", N, " в строке ", i, " ровно ", count)
end

Количество элементов больше 6 в строке 1 ровно 4
Количество элементов больше 6 в строке 2 ровно 2
Количество элементов больше 6 в строке 3 ровно 2
Количество элементов больше 6 в строке 4 ровно 2
Количество элементов больше 6 в строке 5 ровно 3
Количество элементов больше 6 в строке 6 ровно 5


- Определите, в каких строках матрицы 𝑀 число 𝑀 (например, 𝑀 = 7) встречается ровно 2 раза?

In [123]:
M_ = 7

for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] == M_
            count += 1
        end
    end
    if count == 2
        println("Число ", M_, " встречается в строке ", i, " ровно 2 раза")
    end
end

Число 7 встречается в строке 1 ровно 2 раза
Число 7 встречается в строке 3 ровно 2 раза
Число 7 встречается в строке 6 ровно 2 раза


- Определите все пары столбцов матрицы 𝑀, сумма элементов которых больше 𝐾 (например, 𝐾 = 75).

In [127]:
function sum_75(matrix, K)
    matrix_new = rand(10)
    for i in 1:1:10
        sum = 0 
        for j in 1:1:6
            sum += matrix[j, i]
        end
        matrix_new[i] = sum
    end
    # теперь просуммируем все значения matrix_new попарно
    for i in 1:1:10
        for j in i+1:1:10
            sum = matrix_new[i] + matrix_new[j]
            if sum > K
                println("Столбцы - ", i, " и ", j)
            end
        end
    end
end

sum_75 (generic function with 1 method)

In [129]:
sum_75(M, 75)

Столбцы - 5 и 6


<div style="border:solid green 2px; padding: 20px">
11. Вычислите:  
    
$\sum_{i=1}^{20}\sum_{j=1}^5\frac{i^{4}}{3+j}$
    
$\sum_{i=1}^{20}\sum_{j=1}^5\frac{i^{4}}{3+ij}$
</div>

In [131]:
first_sum = 0
for i in 1:1:20
    for j in 1:1:5
        first_sum += (i^4)/(3+j)
    end
end
println(first_sum)

639215.2833333334


In [133]:
second_sum = 0
for i in 1:1:20
    for j in 1:1:5
        second_sum += (i^4)/(3+i*j)
    end
end
println(second_sum)

89912.02146097136
